substitutions:
  _PROJECT1: terraform-asia-southeast2-prod
  _PROJECT2: terraform-europe-west2-prod
  _PROJECT3: terraform-us-east4-prod
  _REGION1: asia-southeast2
  _REGION2: europe-west2
  _REGION3: us-east4
  _ENV: test

steps:
      #-----------asia-southeast2 region---------#
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - config
      - set
      - project
      - ${_PROJECT1} #setting as project 1, as this cloud build trigger is running on PROJECT2 right now
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - functions
      - deploy
      - vf-acs-func-${_REGION1}-${_ENV}
      - --set-env-vars=ENV=${_ENV},REGION=${_REGION1} #this is the project 1 
      - --region=${_REGION1}
      - --source=.
      - --entry-point=myBackgroundFunction
      - --trigger-bucket=ul-vf-${_REGION1}-${_ENV}-terraform-demo #This is the project 1 bucket
      - --runtime=python310

    #-----------us-west1 region---------#
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - config
      - set
      - project
      - ${_PROJECT3} #setting as project 3, as this cloud build trigger is running on PROJECT2 right now
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - functions
      - deploy
      - vf-acs-func-${_REGION3}-${_ENV}
      - --set-env-vars=ENV=${_ENV},REGION=${_REGION3} #this is the project 3
      - --region=${_REGION3}
      - --source=.
      - --entry-point=myBackgroundFunction
      - --trigger-bucket=ul-vf-${_REGION3}-${_ENV}-terraform-demo #This is the project 3 bucket
      - --runtime=python310

      #-----------europe-west2 region---------#
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - config
      - set
      - project
      - ${_PROJECT2} #setting as project 2, as this cloud build trigger is running on PROJECT3 right now due to previous step
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: 
      - gcloud
      - functions
      - deploy
      - vf-acs-func-${_REGION2}-${_ENV}
      - --set-env-vars=ENV=${_ENV},REGION=${_REGION2} #this is the project 2 
      - --region=${_REGION2}
      - --source=.
      - --entry-point=myBackgroundFunction
      - --trigger-bucket=ul-vf-${_REGION2}-${_ENV}-terraform-demo #This is the project 2 bucket
      - --runtime=python310


#_PROJECT2: project-2-364610
#_PROJECT3: project-3-364610
#_REGION1: asia-southeast2
#_REGION2: europe-west2
#_REGION3: us-west1




        #MIGHT WANT TO SE BUILD VARIABLES SO I CAN USE HERE ALSO. CAN PARSE BUILD REGION THROUGH TO RUNTIME ALSO

##-----Below shows how you can add variables into a cloud build.yaml file - using "substitutions"----###https://www.cyberithub.com/deploy-a-container-to-multiple-gcp-projects-and-host-with-cloud-run/  step 5##
##- name: 'gcr.io/cloud-builders/gcloud'
#steps:
#args: ['run','deploy','demo-service','--image','gcr.io/${_ANPROJECT}/${_CONTAINERNAME}/${_VERSION}','--region','us-east1','--platform','managed']
#images:
#- 'gcr.io/${_ANPROJECT}/${_CONTAINERNAME}/${_VERSION}'



      #env:
      #- 'ENVIRONMENT=${_ENV}'
      #- 'REGION=europe-west2'
